//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HartamaViewDashboard.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAction
    {
        public string Action_ID { get; set; }
        public string NotificationID { get; set; }
        public int ActionType { get; set; }
        public string ActionDescription { get; set; }
        public string UserEntry { get; set; }
        public System.DateTime DateEntry { get; set; }
    }
}
